name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
          
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o senderExe sender/sender.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o receiverExe receiver/receiver.cpp
     
    - name: static analysis
      run: cppcheck --force --enable=all --error-exitcode=1 .
    
    - name: run
      run: ./senderExe | ./receiverExe
    
    - name: coverage report Sender
      run: gcov -r sender/sender.cpp
      
    - name: coverage report Receiver
      run: gcov -r receiver/receiver.cpp
