name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o senderExe sender/sender.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o receiverExe receiver/receiver.cpp
    
    - name: run
      run: ./senderExe | ./receiverExe
